services:
  - type: web
    name: fake-dictionary-server
    env: node
    rootDir: server
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: PORT
        value: 10000
